### ISSUE TITLE
Git Push username and e-mail

### ISSUE THREAD

**Issue by kriko** [kestra-io/plugin-git#43]
### Feature description

Currently Git Push when commiting to a repository states that the commit was made by user `root` with an e-mail address of `root@kestra-worker-.......-......`.

If possible change this behaviour to at least use the Git username defined in https://kestra.io/plugins/tasks/io.kestra.plugin.git.Push#username

Screenshot from GitLab.
![image](https://github.com/kestra-io/plugin-git/assets/169998/24e63334-0a88-497e-ba3d-fffbbc94882d)

**Comment by anna-geller** [comment]
Excellent point, I also wondered about this, we should improve this for sure 👍

**Comment by loicmathieu** [comment]
To be able to add the author, we will need to add the email of the author as task property as the username is not enought.

**Comment by loicmathieu** [comment]
In fact author and username are two different things for Git.
I'll add new fields to be able to set the author of the commit.
