### ISSUE TITLE
Rename gitDirectory to namespaceFilesGitDirectory and add a flowsGitDirectory property

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-git#49]
### Feature description

Several users request better support for flows and Namespace Files directories across (potentially nested) namespaces, even for monorepo setups. To better support that, we should allow the Git Sync task to accept a directory for flows instead of assuming a `_flows` directory.

## Proposal
1. Add a `flowsGitDirectory` property, which can be by default set to the `_flows` directory
2. Rename `gitDirectory` to `namespaceFilesGitDirectory` to make it explicit that this is meant only for namespace files, not for flows

By changing those 2 properties, users can use the same repository for multiple flows. Imagine a directory "engineering" can contain all flows for the engineering namespace and all child namespaces, while the "marketing" directory in Git can be used to deploy flows to the "marketing" namespace and any child namespaces of that. At the same time, the user maintains the flexibility to sync specific directories as Namespace Files to one or more of the namespaces.

**Comment by kriko** [comment]
Taking into account the issues  / requests we have around git.Sync and git.Push, also issue #44 then I would propose, the following.

By default, flows synced from and to git, should reside under "/_flows" folder (as per current behaviour).

Git flows for nested namespaces should then be loaded and written to a nested subfolder, I can propose two options for folder and file naming scheme:

1. A more consistent pattern, perhaps better for monorepos, however in case of single layer namespaces then the additional folder might not be ideal.

| Namespace | Flow name | File name in Git |
| --- | --- | --- |
| my-namespace | my-flow | /_flows/my-namespace/my-flow.yml |
| my-namespace.child-namespace | child-flow | /_flows/my-namespace/child-namespace/child-flow.yml |
| my-namespace.child.grandchild | granchild | /_flows/my-namespace/child/grandchild/granchild.yml |

2. More consistent behaviour to the current solution, less subdirectories.

| Namespace | Flow name | File name in Git |
| --- | --- | --- |
| my-namespace | my-flow | /_flows/my-flow.yml |
| my-namespace.child-namespace | child-flow | /_flows/child-namespace/child-flow.yml |
| my-namespace.child.grandchild | granchild | /_flows/child/grandchild/granchild.yml |

In any case, this would also look better in the logs and would be easier to manage, less clutter in the case of hundreds of flows in a namespace.

The behaviour should be consistent between git.Push and git.Clone - ideally, when you push configuration to a git repository, you should be able to sync it in another Kestra instance and get the same result.

**Comment by anna-geller** [comment]
Thanks for the in-depth request. I'll look into this with the team. Just a heads up this might be complex as flows are not meant to be nested folders, flows are just metadata sent to the database (not files like Namespace Files) so we need some standard structure to parse that metadata reliably

**Comment by anna-geller** [comment]
this will be addressed exactly as you suggested in:
- https://github.com/kestra-io/plugin-git/issues/56
- https://github.com/kestra-io/plugin-git/issues/57
