### ISSUE TITLE
Improve revision handling in the SyncFlows task

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-git#68]
### Feature description

@brian-mulier-p I checked the `SyncFlows` implementation again and we need to find a better solution for `revision` handling. At the moment, we display state OVERWRITTEN and `revision 2` even though the synced flows haven't changed and have `revision 1`. This is not only confusing but also displaying `revision 2` while flows have only a single revision is incorrect/misleading. 

![image](https://github.com/kestra-io/plugin-git/assets/86264395/279e108b-708c-4627-97e1-f1a99c386309)

![image](https://github.com/kestra-io/plugin-git/assets/86264395/edaf4aae-a1c6-40ee-be2c-ecb6eb72b973)

We should:
- either find a better solution to read each flow, see what changed, and only if it changed show state `OVERWRITTEN` and increment its revision; sure, some race condition could happen that while you check subsequent flows, the previous flow might have changed, but this is an edge case we can deliberately take out of scope for now
- or remove the revision property from the output (worst case, it would be better to have it; still, if we can't find a better revision handling, better to remove that from the output entirely)

Ofc it will take longer if we read the flow contents but optimizing the performance of this task is not an issue at this stage 👍

**Comment by brian-mulier-p** [comment]
That's exactly what I wanted to showcase you while in huddle friday evening (or something). But sure we can read all files and be lazy about performance for now :+1:
