### ISSUE TITLE
Git plugin new task QA

### ISSUE THREAD

**Issue by Skraye** [kestra-io/plugin-git#71]
### Expected Behavior

Add `.git` if not set in the URL
Replace regex match with ant style

### Environment Information

- Kestra Version:
- Plugin version: 
- Operating System (OS / Docker / Kubernetes):
- Java Version (If not docker):

**Comment by brian-mulier-p** [comment]
To keep track of: I didn't add the auto add ".git" feature as I'm afraid some provider are expecting URLs without it
