### ISSUE TITLE
io.kestra.plugin.git.SyncFlows not working with Azure git

### ISSUE THREAD

**Issue by HeribertoAlves** [kestra-io/plugin-git#72]
### Expected Behavior

Sync all flow on Kestra

### Actual Behaviour

Illegal flow yaml: Cannot construct instance of `io.kestra.core.models.flows.Flow` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('.')
 at [Source: (StringReader); line: 1, column: 1]

### Steps To Reproduce

Just create a flow and execute it.

All my flows area on folder flows/cnae on git 

### Environment Information

- Kestra Version: 0.17.1
- Plugin version: 
- Operating System (OS / Docker / Kubernetes): Docker
- Java Version (If not docker):

### Example flow

id: syc_flows_from_gitazure
namespace: timoneiro.online
description: Sincronizar os fluxos salvos no git

labels:
  project: tim.datawarehouse
  environment: prod
  client: all
  target: gitsync

tasks:
  - id: sync_flows
    type: io.kestra.plugin.git.SyncFlows
    url: https://feesc-ti@dev.azure.com/feesc-ti/Timoneiro/_git/flows
    targetNamespace : "tim.online"
    branch: master
    #dryRun: true
    #delete: true
    gitDirectory: flows
    includeChildNamespaces: true
    username: "{{ secret('DBSCONFIGUSER') }}"
    password: "{{ secret('GITSYSFLOWPASS') }}"

**Comment by HeribertoAlves** [comment]
On targetNamespace I've tried tim, "tim" as well. 

I have another flow and I use io.kestra.plugin.git.Clone with no problem

**Comment by HeribertoAlves** [comment]
I figure it out! 

I tried on Gitlab and got the error:
Illegal flow yaml: No content to map due to end-of-input at [Source: (StringReader); line: 1, column: 1]

But when I deleted all .gitkeep from all repository I was able to sync.

So I went back to Azure and delete .gitignore file that existed. Synced without problem! 

Hope this help!

**Comment by brian-mulier-p** [comment]
Hello ! Sorry for the inconvenience I forgot to ignore .git** files, done and will be available in the next bugfix release (0.17.3)
